token: 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
scrape_interval: 30
port: 9988
runner:
  enabled: true
  org: er-x
workflow:
  enabled: true
  owner: er-x
  list:
    - owner: er-x
      repo: fe-sky-blue-dashboard
    - repo: fe-sky-blue-exchange
    - repo: fe-one-circle-web
    - repo: fe-sky-blue-2fa
    - repo: fe-sky-blue-cms
