token: github_personal_access_tokens_OR_fine_grained_access_tokens # require
scrape_interval: 15 # optional
port: 9988 # optional
runner: # optional
  enabled: true
  org: organization_name
workflow: # optional
  enabled: true
  owner: owner_name # optional, apply to all list
  list:
    - owner: owner_name # optional, override workflow.owner
      name: custom_name # optional, name for github_workflow_status
      repo: repo_name_1
    - repo: repo_name_2
